workflows:
  ionic-capacitor-ios:
    name: Arcana iOS Build
    max_build_duration: 120
    environment:
      node: 22.3.0
      xcode: latest
      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Give permission
        script: chmod +x node_modules/.bin/cap
      - name: Add iOS platform
        script: node_modules/.bin/cap add ios || true
      - name: Capacitor sync
        script: node_modules/.bin/cap sync ios
      - name: Set up API key
        script: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo -n "$APP_STORE_CONNECT_PRIVATE_KEY" > ~/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8
      - name: Build iOS
        script: |
          xcodebuild \
            -workspace ios/App/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath build/App.xcarchive \
            -allowProvisioningUpdates \
            -authenticationKeyPath $HOME/.appstoreconnect/private_keys/AuthKey_$APP_STORE_CONNECT_KEY_IDENTIFIER.p8 \
            -authenticationKeyID $APP_STORE_CONNECT_KEY_IDENTIFIER \
            -authenticationKeyIssuerID $APP_STORE_CONNECT_ISSUER_ID \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=NZLX757KSZ \
            archive
    artifacts:
      - build/App.xcarchive
      - /tmp/xcodebuild_logs/*.log